name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Download freewrap
    #   run: |
    #     sudo wget https://sourceforge.net/projects/freewrap/files/freewrap/freeWrap%206.75/freewrap675.tar.gz/download -O ./freewrap.tar.gz
    # - name: Cache freewrap
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ github.workspace }}/freewrap.tar.gz
    #     key: ${{ runner.os }}-freewrap-${{ hashFiles('freewrap.tar.gz') }}
    #     restore-keys: |
    #       ${{ runner.os }}-freewrap-
    #       ${{ runner.os }}-
    # - name: Unzip freewrap
    #   run: |
    #     sudo tar -xzf ./freewrap.tar.gz
    # - name: Check path of freewrap
    #   run: |
    #     echo $ls
    # - name: Check path of freewrap
    #   run: |
    #     echo $(ls ./freewrap/linux64/freewrap)
    - name: Change perms freewrap
      run: |
        sudo chmod +x ./freewrap
    - name: Build executable
      run: |
        sudo ./freewrap ./gui.tcl
      continue-on-error: true
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%dT%H_%M')"
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CACHE_ON_FAILURE: true
      with:
        tag_name: ${{ steps.date.outputs.date }}
        name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        files: |
          gui
        # file_name: perlink_amd64_windows
        body: |
          - ${{ github.event.head_commit.message }} ${{ github.sha }}