name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install freewrap
      run: |
        wget https://sourceforge.net/projects/freewrap/files/freewrap/freeWrap%206.73/freewrap673.tar.gz/download -O freewrap.tar.gz
        tar -xzf freewrap.tar.gz
        chmod +x freewrap673/freewrap
    - name: Build executable
      run: |
        ./freewrap673/freewrap gui.tcl -o gui
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%dT%H_%M')"
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CACHE_ON_FAILURE: true
      with:
        tag_name: ${{ steps.date.outputs.date }}
        name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        files: |
          gui
        # file_name: perlink_amd64_windows
        body: |
          - ${{ github.event.head_commit.message }} ${{ github.sha }}